export default {
	MESSAGE_CREATED: 'MESSAGE_CREATED',
	MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',

	PROFILE_CREATED: 'PROFILE_CREATED',
	PROFILE_RECEIVED: 'PROFILE_RECEIVED',
	USER_LOGGED_IN: 'USER_LOGGED_IN',

	TASKS_RECEIVED: 'TASKS_RECEIVED',
	TASK_CREATED: 'TASK_CREATED',

	CATEGORY_SELECTED: 'CATEGORY_SELECTED'
}